# Generated by Django 5.1.5 on 2025-02-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_rename_is_provider_customuser_is_business_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='Benutzername', max_length=100)),
                ('first_name', models.CharField(default='Vorname', max_length=100)),
                ('last_name', models.CharField(default='Nachname', max_length=100)),
                ('file', models.FileField(blank=True, null=True, upload_to='profile_pics')),
                ('location', models.CharField(default='Stadt', max_length=100)),
                ('tel', models.CharField(default='0123456789', max_length=100)),
                ('type', models.CharField(choices=[('business', 'business'), ('customer', 'customer')], default='customer', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(default='email', max_length=254, unique=True)),
                ('description', models.TextField(default='Beschreibung')),
                ('working_hours', models.TextField(default='09:00 - 18:00')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
