# Generated by Django 5.1.5 on 2025-02-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_profile_uploaded_at_alter_profile_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(error_messages={'unique': 'Email existiert bereits.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='First Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='Last Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=models.CharField(default='0123456789', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(default='Your Name', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='working_hours',
            field=models.CharField(default='09:00 - 18:00', max_length=100),
        ),
    ]
