# Generated by Django 5.1.5 on 2025-02-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_info', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessProfile',
        ),
    ]
