# Generated by Django 5.1.5 on 2025-02-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerdetails',
            old_name='offerTypes',
            new_name='offer_type',
        ),
    ]
