# Generated by Django 5.1.5 on 2025-02-16 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offers', '0003_alter_offer_title_offerdetail_delete_offerdetails'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'In Bearbeitung'), ('completed', 'Abgeschlossen'), ('cancelled', 'Abgebrochen')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('offer_type', models.CharField(blank=True, max_length=50)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_time_in_days', models.IntegerField(blank=True, null=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('revisions', models.IntegerField(blank=True, null=True)),
                ('customer_user', models.IntegerField(default=0)),
                ('business_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Business User')),
                ('offer_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='offers.offerdetail', verbose_name='OfferDetail')),
            ],
        ),
    ]
